#!/bin/sh
set -e
case "$1" in
  purge)
    rm -rf /opt/baxters/iris
    rmdir /opt/baxters 2>/dev/null || true
    [ -x /usr/bin/update-desktop-database ] && update-desktop-database -q /usr/share/applications || true
    ;;
esac
exit 0
